function createTaxDebitNotetAction(request, response) {
  nlapiLogExecution('DEBUG', 'getting inside');
  var recordID = request.getParameter('recordID');
  nlapiLogExecution('DEBUG', 'recordID', recordID);

  var taxdebitnote = nlapiLoadRecord("vendorcredit", recordID);
  var renderer = nlapiCreateTemplateRenderer();
  var template = "";
  var count = taxdebitnote.getLineItemCount('item');


  var subsidiary = taxdebitnote.getFieldValue('subsidiary');
  var sub = nlapiLoadRecord("subsidiary", subsidiary);



  template += '<?xml version="1.0"?><!DOCTYPE pdf PUBLIC "-//big.faceless.org//report" "report-1.1.dtd">';
  template += '<pdf>';
  template += '<head>';
  template += '<link name="NotoSans" type="font" subtype="truetype" src="${nsfont.NotoSans_Regular}" src-bold="${nsfont.NotoSans_Bold}" src-italic="${nsfont.NotoSans_Italic}" src-bolditalic="${nsfont.NotoSans_BoldItalic}" bytes="2" />';
  template += '<#if .locale == "zh_CN">';
  template += '<link name="NotoSansCJKsc" type="font" subtype="opentype" src="${nsfont.NotoSansCJKsc_Regular}" src-bold="${nsfont.NotoSansCJKsc_Bold}" bytes="2" />';
  template += '<#elseif .locale == "zh_TW">';
  template += '<link name="NotoSansCJKtc" type="font" subtype="opentype" src="${nsfont.NotoSansCJKtc_Regular}" src-bold="${nsfont.NotoSansCJKtc_Bold}" bytes="2" />';
  template += '<#elseif .locale == "ja_JP">';
  template += '<link name="NotoSansCJKjp" type="font" subtype="opentype" src="${nsfont.NotoSansCJKjp_Regular}" src-bold="${nsfont.NotoSansCJKjp_Bold}" bytes="2" />';
  template += '<#elseif .locale == "ko_KR">';
  template += '<link name="NotoSansCJKkr" type="font" subtype="opentype" src="${nsfont.NotoSansCJKkr_Regular}" src-bold="${nsfont.NotoSansCJKkr_Bold}" bytes="2" />';
  template += '<#elseif .locale == "th_TH">';
  template += '<link name="NotoSansThai" type="font" subtype="opentype" src="${nsfont.NotoSansThai_Regular}" src-bold="${nsfont.NotoSansThai_Bold}" bytes="2" />';
  template += '</#if>';
  template += '<macrolist>';
  template += '<macro id="nlheader">';

  template += '';
  template += ' ';
  template += '   ';
  template += '';
  template += '   <table style="width: 100%;margin-top:5px;">';
  template += '   <tr>';
  template += '   ';
  template += '';

  if (sub != "") {
    var address = sub.getFieldValue('mainaddress_text');


    // template+=' <td align="left" width="50%">' +relaceSlashN(address)+ '</td>';
    template += '            <td align="left" width="60%"><p align="left" width="60%"><b>Nasser Abdullah LootahGroup(LLC)</b> <br/>' + relaceSlashN(address) + '</p></td>  ';
    template += '';

    if (subsidiary == 3) {
      template += '            <td align="right" valign="top" width="33%">';
      template += '';
      template += '                <img src="${record.custbody_subsidiary_logo.imageUrl}" style="width:220px;height:180px;margin:60px;position:absolute;top:-10px;padding-top:-120px;padding-left:-60px;" />';
      template += '';

      template += '            </td>';
    } else if (subsidiary == 4) {

      template += '            <td align="right" valign="top" width="33%">';
      template += '';
      template += '                <img src="${record.custbody_subsidiary_logo.imageUrl}" style="width:200px;height:130px;margin:60px;position:absolute;top:-10px;padding-top:-100px;padding-left:-60px;" />';
      template += '';

      template += '            </td>';
    }
    template += '  </tr>';

    template += '            <tr>';
    template += '            <td></td>';
    template += '            </tr>       ';
    template += '';
    template += '    ';
    template += '    <tr>';
    // var country = sub.getFieldValue('country');
    template += ' <td align="left" width="50%"></td>';

  }
  template += '        ';
  template += '        <td width="40%">';
  template += '            <table style="width:100%; padding-top:35px;">';
  template += '                <tr>';
  template += '                    <td width="50% "><p align="left; padding-top:-95px;">Telephone</p></td>';
  template += '                    <td width="50%"></td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td><p align="left">Fax</p></td>';
  template += '                    <td></td>';
  template += '                </tr>';
  template += '              <!---  <tr>';
  template += '                    <td><p align="left">Giro</p></td>';
  template += '                    <td></td>';
  template += '                </tr>-->';
  template += '               ';
  template += '';
  template += '                <tr>';
  template += '                    <td><p align="left">Tax Registration Number</p></td>';
  template += '                    <td><p align="left"></p>${subsidiary.federalidnumber}</td>';
  template += '                </tr>  ';
  template += '            </table>';
  template += '        </td>';
  template += '    </tr> ';
  template += '    <tr>   ';
  template += '       <td width="58%">${record.defaultaddress}<br></br>Tax Registration Number &nbsp; ${record.entity.vatregnumber}</td>';
  template += '        <td>';
  template += '             <table style="width:100%">';
  template += '                <tr>';
  template += '                   <td colspan="2"><p align="left"><h2>TAX DEBIT NOTE</h2></p> </td>';
  template += '                </tr>';
  template += '               <!--- <tr>';
  template += '                ';
  template += '                <td>';
  template += '             <table style="width:100%">';
  template += '                <tr>';
  template += '                     <td width="40%"><b>Shipping Destination</b></td>';
  template += '                    <td width="2%"><b>:</b></td>';
  template += '                    <td width="58%">${subsidiary.mainaddress_text}</td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td align="left" width="64%">Tax Registration Number</td>';
  template += '                    <td align="left" width="1%"><b>:</b></td>';
  template += '                    <td align="left" width="64%">${subsidiary.federalidnumber}</td>';
  template += '                </tr>';
  template += '               ';
  template += '               <tr>';
  template += '                     <td><b>Memo</b></td>';
  template += '                    <td><b>:</b></td>';
  template += '                    <td> NASSER ABDULLA LOOTAH GROUP(LLC)</td>';
  template += '                </tr>';
  template += '            </table>';
  template += '        </td>';
  template += '                </tr>-->';
  template += '               <tr>';
  template += '                   <td><p align="left">Number</p></td>';
  template += '                   <td align="left">${record.memo}</td>';
  template += '                </tr>';
  template += '                 <tr>';
  template += '                   <td><p align="left">Date</p></td>';
  template += '                   <td align="left">${record.trandate}</td>';
  template += '                </tr>';
  template += '                 <tr>';
  template += '                   <td><p align="left">Page</p></td>';
  template += '                ';
  template += '             <td> &nbsp; <pagenumber/>of <totalpages/>&nbsp;</td>';
  template += '';
  template += '';
  template += '                   ';
  template += '                </tr>';
  template += '                 <tr>';
  template += '                   <td><p align="left">Purchase Order</p></td>';
  template += '                   <td align="left">${record.tranid}</td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td align="left">Internal number</td>';
  template += '                     <td align="left">${record.transactionnumber}</td>';
  template += '                </tr>';
  template += '                 <tr>';
  template += '                    <td align="left">Payment</td>';
  template += '                     <td align="left">${record.duedate}</td>';
  template += '                </tr>';
  template += '';
  template += '              <!---   <tr>';
  template += '                    <td colspan="2"><p align="left">Delivery address<br></br>${subsidiary.mainaddress_text}</p></td>';
  template += '';
  template += '                </tr>-->';
  template += '';
  template += '            </table>';
  template += '        </td>';
  template += '    </tr>';
  template += '     <tr>';
  template += '    <!--    <td>';
  template += '            <table style="width:100%;margin-top:50px">';
  template += '               <tr>';
  template += '                    <td width="35%"><p align="left"><b>Main Account</b></p></td>';
  template += '                    <td width="2%"><b>:</b></td>';
  template += '                    ';
  template += '                    <td width="63%"><p align="left"><b>${record.entity.accountnumber}</b></p></td>';
  template += '                    ';
  template += '                </tr>';
  template += '                ';
  template += '   ';
  template += '                <tr>';
  template += '                    <td><p align="left"><b>Main Account Name</b></p></td>';
  template += '                    <td ><b>:</b></td>';
  template += '                    <td><p align="left">${record.entity}</p></td>';
  template += '                </tr>';
  template += '                ';
  template += '';
  template += '                <tr>';
  template += '                    <td><p align="left"><b>Address</b></p></td>';
  template += '                    <td ><b>:</b></td>';
  template += '                    <td><p align="left">${record.billaddress}</p></td>';
  template += '                </tr>';
  template += '               ';
  template += '';
  template += '                <tr>';
  template += '                    <td><p align="left"><b>Tax Reg No</b></p></td>';
  template += '                    <td ><b>:</b></td>';
  template += '                    <td><p align="left">${record.entity.vatregnumber}</p></td>';
  template += '                </tr>';
  template += '            </table>';
  template += '        </td>-->';
  template += '     ';
  template += '    </tr>';
  template += '    </table>';
  template += '</macro>';
  template += '<#if (record.status == "Pending Approval") >';
  template += '                            <macro id="watermark">';
  template += '<div rotate="-45" style="margin-top:400px;margin-left:50px;margin-right:50px;z-index:999;" font-size="20pt" color="#C0C0C0">';
  template += '<p>PENDING FOR APPROVAL</p>';
  template += '</div>';
  template += '</macro>';
  template += '</#if>';
  template += '';
  template += '                            <macro id="nlfooter">';
  template += '                            <!---    <table style="width: 100%;">';
  template += '                                    <tr>';
  template += '                                        <td align="left" style="width:60%;">';
  template += '                                            <p class="alignL" style="font-size:11px;font-style:italics;color:#A9A9A9">*This is a system-generated document. No signature is required.</p>';
  template += '                                        </td>';
  template += '';
  template += '                                        <td style="margin-left:150px;">&nbsp;( Page <pagenumber/>';
  template += ' of <totalpages/>';
  template += ' )&nbsp;</td>';
  template += '                                </tr>';
  template += '';
  template += '';
  template += '';
  template += '                            </table>-->';
  template += '                        </macro>';
  template += '                    </macrolist>';
  template += '                    <style type="text/css">span, table {';
  template += '                        <#if .locale=="zh_CN">font-family: stsong, sans-serif;';
  template += '                            <#elseif .locale=="zh_TW">font-family: msung, sans-serif;';
  template += '                                <#elseif .locale=="ja_JP">font-family: heiseimin, sans-serif;';
  template += '                                    <#elseif .locale=="ko_KR">font-family: hygothic, sans-serif;';
  template += '                                        <#elseif .locale=="ru_RU">font-family: verdana;';
  template += '                                            <#else>font-family: sans-serif;';
  template += '                                            </#if>font-size: 9pt;';
  template += '		table-layout: fixed;';
  template += '		}';
  template += '		th {';
  template += '		font-weight: bold;';
  template += '		font-size: 8.5pt;';
  template += '		padding-top: 2px;';
  template += '		vertical-align: middle;';
  template += '		/*padding: 3px 6px 10px;*/';
  template += '		/*background-color: #e3e3e3;';
  template += '		color: #333333;*/';
  template += '		}';
  template += '		b {';
  template += '		font-weight: bold;';
  template += '		color: #333333;';
  template += '		}';
  template += '		table.header td {';
  template += '		padding: 0;';
  template += '		font-size: 10pt;';
  template += '		}';
  template += '		table.footer td {';
  template += '		padding: 0;';
  template += '		font-size: 8pt;';
  template += '		}';
  template += '		#itemtable th p{';
  template += '		vertical-align: text-top !important;';
  template += '		text-align: center !important;';
  template += '		}';
  template += '		#itemtable{';
  template += '		font-size: 8.5pt !important;';
  template += '		border: 0.5px solid #000000';
  template += '		}';
  template += '		table.total {';
  template += '		page-break-inside: avoid;';
  template += '		}';
  template += '		tr.totalrow {';
  template += '		background-color: #e3e3e3;';
  template += '		line-height: 200%;';
  template += '		}';
  template += '		td.totalboxtop {';
  template += '		font-size: 12pt;';
  template += '		background-color: #e3e3e3;';
  template += '		}';
  template += '		span.title {';
  template += '		font-size: 28pt;';
  template += '		}';
  template += '		.smallTitle {';
  template += '		font-size: 9pt;';
  template += '		}';
  template += '		span.number {';
  template += '		font-size: 16pt;';
  template += '		text-align:center;';
  template += '		}';
  template += '		span.itemname {';
  template += '		font-weight: bold;';
  template += '		line-height: 150%;';
  template += '		}';
  template += '		hr {';
  template += '		width: 100%;';
  template += '		color: #d3d3d3;';
  template += '		background-color: #d3d3d3;';
  template += '		height: 1px;';
  template += '		}';
  template += '		table.smalltext tr td {';
  template += '		font-size: 8pt;';
  template += '		}';
  template += '		/*table.itemtable th{';
  template += '		border-bottom: 10px #ffc966;';
  template += '		border-color: yellow;';
  template += '		}*/';
  template += '		p.alignR {';
  template += '		text-align: right !important;';
  template += '		}';
  template += '		p.alignL {';
  template += '		text-align: left !important;';
  template += '		}';
  template += '		p.alignC {';
  template += '		text-align: center !important;';
  template += '		}';
  template += '		.td_right_line{';
  template += '		/*border-right: 0.5px solid #f4f4f4;*/';
  template += '		border-right :0.5px solid #000000;';
  template += '		}';
  template += '		.td_bottom_line{';
  template += '		border-bottom: 0.5px solid #000000;';
  template += '		}';
  template += '		.td_top_line{';
  template += '		/*border-top :0.5px solid #f4f4f4;*/';
  template += '		border-top :0.5px solid #000000;';
  template += '		}';
  template += '		.title{';
  template += '		font-weight: bold;';
  template += '		align:center!important;';
  template += '		font-size:16pt;';
  template += '		}';
  template += '		.footer-img{';
  template += '		/*width: 100%;';
  template += '		height: 20%;*/';
  template += '		top: 0px;';
  template += '		right: 0px;';
  template += '		left: 0px;';
  template += '		bottom: 0px;';
  template += '		}';
  template += '		.footer{';
  template += '		margin-left:-45px; margin-right:-60px; margin-bottom:-115px;';
  template += '		}';
  template += '		.td_left_line{';
  template += '		/*border-right: 0.5px solid #f4f4f4;*/';
  template += '		border-left :0.5px solid #000000;';
  template += '		}';
  template += '		.maintbl{';
  template += '		border:0.5px solid #000000;';
  template += '		}';
  template += '		.footertbl{';
  template += '		border:0.5px solid #000000;';
  template += '		border-top: 0px !important;';
  template += '		}';
  template += '		.footertbl2{';
  template += '		';
  template += '		/*border:0.5px solid #000000;*/';
  template += '		border-left: 0.5px solid #000000;';
  template += '		border-right: 0.5px solid #000000;';
  template += '		border-top: 0.25px !important;';
  template += '		}';
  template += '		.pad_left{';
  template += '		padding-left: 5px!important;';
  template += '		}';
  template += '		th,td{';
  template += '		padding:4px;';
  template += '		}';
  template += '		                                                                                                                                                                                                                            <!--  .td_top_line td{';
  template += '		padding-left: 5px!important;';
  template += '		} -->';
  template += '		td img {';
  template += '		max-width:100%;';
  template += '		';
  template += '		}';
  template += '                                        </style>';
  template += '                                    </head>';
  template += '                                    <body header="nlheader" background-macro="watermark" header-height="40%" footer="nlfooter" footer-height="4%" padding="0.25in 0.5in 0.25in 0.5in" size="A4">';
  template += ' <table style="width:100%">';
  template += '           <!--<tr><td align="center" class="title">';
  template += '                                                    <u>TAX INVOICE</u>';
  template += '                                                </td></tr>';
  template += '    </table>';
  template += '   <table style="width: 100%;margin-bottom:-60px;">';
  template += '    <tr>';
  template += '        <td>';
  template += '            <table style="width:100%">';
  template += '                 <tr>';
  template += '                    <td width="35%"><p align="left"><b>Customer</b></p></td>';
  template += '                    <td width="2%"><b>:</b></td>';
  template += '                     <#if record.entity.isperson?string == "Yes">';
  template += '                    <td><b>${record.entity.firstname}&nbsp;${record.entity.lastname}</b></td>';
  template += '                    <#else>';
  template += '                    <td width="63%"><p align="left"><b>${record.entity.companyname}</b></p></td>';
  template += '                     </#if>';
  template += '                </tr>';
  template += '                 <tr>';
  template += '                    <td><p align="left"><b>Invoice No</b></p></td>';
  template += '                    <td ><b>:</b></td>';
  template += '                    <td><p align="left">${record.tranid}</p></td>';
  template += '                </tr> ';
  template += '                <tr>';
  template += '                    <td width="35%"><p align="left"><b>Invoice Date</b></p></td>';
  template += '                    <td width="2%"><b>:</b></td>';
  template += '                    <td width="63%"><p align="left">${record.trandate?string("dd-MMM-YYYY")}</p></td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td><p align="left"><b>Date of Supply</b></p></td>';
  template += '                    <td ><b>:</b></td>';
  template += '                    <td><p align="left">${record.startdate}</p></td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td><p align="left"><b>Customer Reference</b></p></td>';
  template += '                    <td ><b>:</b></td>';
  template += '                    <td><p align="left">${record.custbody_nalg_customer_ref}</p></td>';
  template += '                </tr>';
  template += '               ';
  template += '            </table>';
  template += '        </td>';
  template += '        <td >';
  template += '             <table style="width:100%">';
  template += '                <tr>';
  template += '                    <td width="40%"><b>Sales Order NO</b></td>';
  template += '                    <td width="2%"><b>:</b></td>';
  template += '                    <td width="58%">${record.custbody_rent_sales_order}</td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td><b>Payment Terms</b></td>';
  template += '                    <td><b>:</b></td>';
  template += '                    <td>${record.terms}</td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td><b>Invoice Amount</b></td>';
  template += '                    <td><b>:</b></td>';
  template += '                    <td> ${record.currency}</td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td><b>Sales Person</b></td>';
  template += '                    <td><b>:</b></td>';
  template += '                    <td> ${record.salesrep}</td>';
  template += '                </tr>';
  template += '               ';
  template += '                ';
  template += '            </table>';
  template += '        </td> ';
  template += '    </tr>';
  template += '      <tr>';
  template += '        <td>';
  template += '            <table style="width:100%">';
  template += '                <tr>';
  template += '                    <td width="40%"><p align="left"><b>Dispatch Document#</b></p></td>';
  template += '                    <td width="2%"><b>:</b></td>';
  template += '                    <td>${record.custbody_nalg_dispatch_document}</td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td><p align="left"><b>Dispatched Through</b></p></td>';
  template += '                    <td ><b>:</b></td>';
  template += '                    <td><p align="left">${record.custbody_nalg_dispacthed_through}</p></td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td><p align="left"><b>Delivery Note</b></p></td>';
  template += '                    <td ><b>:</b></td>';
  template += '                    <td><p align="left">${record.custbody_delivery_note}</p></td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td><p align="left"><b>Delivery Note Date</b></p></td>';
  template += '                    <td ><b>:</b></td>';
  template += '                    <td><p align="left">${record.custbody_delivery_note_date}</p></td>';
  template += '                </tr>';
  template += '            </table>';
  template += '        </td>';
  template += '        <td style="border-left:0.5px Solid Black;">';
  template += '             <table style="width:100%">';
  template += '                <tr>';
  template += '                    <td width="40%"><b>Shipping Destination</b></td>';
  template += '                    <td width="2%"><b>:</b></td>';
  template += '                    <td width="58%">${record.custbody_shipping_destination}</td>';
  template += '                </tr>';
  template += '                <tr>';
  template += '                    <td><b>Place of Supply</b></td>';
  template += '                    <td><b>:</b></td>';
  template += '                    <td>${record.custbody_place_of_supply}</td>';
  template += '                </tr>';
  template += '               ';
  template += '                <tr>';
  template += '                    <td><b>Memo</b></td>';
  template += '                    <td><b>:</b></td>';
  template += '                    <td> ${record.memo}</td>';
  template += '                </tr>';
  template += '            </table>';
  template += '        </td>';
  template += '    </tr> -->';
  template += '    </table>';
  template += '    ';
  var j = 1;
  template += ' <#if record.item?has_content>';
  template += '<#assign SrNo=0>';
  template += '<table style="width: 100%;margin-top:-15px;" width="100%">                                                <!-- start items -->';
  template += '                                                <#assign SrNo=0><#assign qty_to_ord = 0 ><#list record.item as item><#if item_index==0><#assign totalamount= 0>';
  template += '                                                <#assign totaltaxamount= 0><#assign totalgrossamount= 0>';
  template += '<thead>';
  template += '<tr style="padding-bottom: 0px;">';
  template += '                                                    <th align="center" width="15%" class="td_bottom_line">';
  template += '                                                        <p align="center">';
  template += '                                                            <b>Sr.No.#</b>';
  template += '                                                        </p>';
  template += '                                                    </th>';
  template += '                                                     <th align="center" class="td_bottom_line" width="15%">';
  template += '                                                        <p class="alignC">Item Number</p>';
  template += '                                                    </th>';
  template += '                                                    <th align="left" class="td_bottom_line" width="15%">';
  template += '                                                        <p class="alignL">Description</p>';
  template += '                                                    </th>';
  template += '                                                    <th align="right" class="td_bottom_line" width="15%">';
  template += '                                                        <p class="alignR">Quantity</p>';
  template += '            ';
  template += '                                                    </th>';
  template += '                                                    <th align="right" class="td_bottom_line" width="15%">';
  template += '                                                        <p class="alignR">Unit</p>';
  template += '            ';
  template += '                                                    </th>';
  template += '                                                    <th align="center" class="td_bottom_line" width="15%">';
  template += '                                                        <p>Unit price </p>';
  template += '                                                    </th>';
  // template+='                                                    <th align="center" class="td_bottom_line" width="15%">';
  // template+='                                                        <p>Discount percent</p>';
  // template+='                                                    </th>';
  template += '                                                   ';
  // template+='                                                    <th align="right" class="td_bottom_line" width="9%">';
  // template+='                                                        <p class="alignR">Discount</p>';
  // template+='                                                    </th>';
  template += '                                                   ';
  template += '                                                    <th align="right" class="td_bottom_line" width="15%">';
  template += '                                                        <p class="alignR">VAT</p>';
  template += '                                                    </th>';
  template += '                                                    ';
  template += '                                                    <th align="right" class="td_bottom_line" width="10%">';
  template += '                                                        <p class="alignR">Amount</p>';
  template += '                                                    </th>';
  template += '                                                </tr>';
  template += '                                            </thead>';
  template += '                                        </#if>';
  template += '</#list>';
  // template += '                                        <#if item.itemtype!="Discount" && item.itemtype!="Subtotal">';
  nlapiLogExecution('DEBUG', 'j============', j);
  var totalgrossamount = 0;
  var totalamount = 0;
  var totaltax1amt = 0;
  for (var i = 1; i <= count; i++) {
    var item = taxdebitnote.getLineItemValue('item', 'item', i);
    var itemNo = nlapiLookupField('item', item, 'itemid');
    nlapiLogExecution('DEBUG', 'Items1111', itemNo);

    j++;
    template += '                                            <tr>';
    // for (var i = 1; i <= count; i++) {
    //     var item = new Array();
    //     var discount = new Array();
    //     var discountpercent = new Array();
    //     item.push(taxdebitnote.getLineItemValue('item', 'item', i))
    //     nlapiLogExecution('DEBUG', 'item', item);
    template += '                                                <td align="center" class="">';
    template += '                                                    <p align="center">';
    template += '                                                        <#assign SrNo=SrNo + 1/>${SrNo}</p></td>';
    template += '<td align="left" class="">';
    template += '                                                            <p class="alignC">' + itemNo + '</p>';
    template += '                                                        </td>';
    template += '                                                         <!-- <td align="center" class="">';
    template += '                                                            <p class="alignC">${item.custcol_upc_code}</p>';
    template += '                                                        </td> -->';
    var description = taxdebitnote.getLineItemValue('item', 'description', i);
    template += '                                                         <td align="left" class="">';
    template += '                                                            <p class="alignL">' + description + '</p>';
    template += '                                                        </td>';
    var quantity = taxdebitnote.getLineItemValue('item', 'quantity', i);
    template += '                                                        <td align="right" class="">';
    template += '                                                            <p class="alignR">' + quantity + '</p>';
    template += '                                                        </td>';
    var units = taxdebitnote.getLineItemValue('item', 'units', i);
    template += '                                                         <td align="right" class="">';
    template += '                                                            <p class="alignR">' + units + '</p>';
    template += '                                                        </td>';
    var rate = taxdebitnote.getLineItemValue('item', 'rate', i);
    template += '                                                         <td align="center" class="">';
    template += '                                                            <p class="alignC">' + rate + '</p>';
    template += '                                                        </td>';
    template += '                                                        ';
    template += '';
    // template+='                                                        <td align="right" class="">';
    // template+='                                                            <p class="alignR"></p>';
    // template+='                                                        </td>';
    template += '                                                        ';
    template += '';
    // template+='';
    // template+='                                                          <td align="right" class="">';
    // template+='                                                            <p class="alignR"></p>';
    // template+='                                                        </td>';
    template += '';
    template += '                                                       ';
    var tax1amt = taxdebitnote.getLineItemValue('item', 'tax1amt', i);
    template += '                                                        <td align="right" class="">';
    template += '                                                            <p class="alignR">' + tax1amt + '</p>';
    template += '                                                        </td>';
    template += '                                                       ';
    // template+='                                                        <td align="right" class="">';
    // template+='                                                            <p class="alignR">${item.amount?string("##,#00.000")}</p>';
    // template+='                                                            </td>';
    // template+='                                                             <td align="center" class="">';
    // template+='                                                            <p class="alignC"></p>';
    // template+='                                                        </td>';
    // template+='                                                       ';
    // template+='                                                        ';
    var grossamt = taxdebitnote.getLineItemValue('item', 'grossamt', i);
    totalgrossamount = parseFloat(totalgrossamount) + parseFloat(grossamt);
    template += '                                                        <td align="right" >';
    template += '                                                         <p class="alignR">';
    template += '                                                                                ' + grossamt + '</p>';

    template += '';
    template += '                                                    ';
    template += '</td>';
    var amount = taxdebitnote.getLineItemValue('item', 'amount', i);
    totalamount = parseFloat(totalamount) + parseFloat(amount);
    var tax1amt = taxdebitnote.getLineItemValue('item', 'tax1amt', i);
    totaltax1amt = parseFloat(totaltax1amt) + parseFloat(tax1amt);
    template += '                                                                                 <#assign totalamount=totalamount + item.amount/>';
    template += '                                                                                    <#assign totaltaxamount=totaltaxamount + item.tax1amt/>';

    template += '</tr>';
  }

  // template += '</#if>';

  template += ' ';

  template += '';
  template += '';
  template += '<!--<tr>';
  template += '<td align="right" colspan="5" class="td_right_line  td_top_line" style="font-weight: bold;">TOTAL</td>';
  template += '                                                                               ';
  template += '                                                                                <td align="right" class="td_top_line td_right_line ">';
  template += '                                                                                    <p class="alignR">';
  template += '                                                                                        <b>' + totalamount + '</b>';
  template += '                                                                                    </p>';
  template += '                                                                                </td>';
  template += '                                                                            ';
  template += '                                                                                <td align="right" class="td_top_line td_right_line ">';
  template += '                                                                                    <p class="alignR">';
  template += '                                                                                        <b></b>';
  template += '                                                                                    </p>';
  template += '                                                                                </td>';
  template += '                                                                                <td align="right" class="td_top_line td_right_line ">';
  template += '                                                                                    <p class="alignR">';
  template += '                                                                                        <b>' + totaltax1amt + '</b>';
  template += '                                                                                    </p>';
  template += '                                                                                </td>';
  template += '                                                                                ';
  template += '                                                                               ';
  template += '                                                                                ';
  template += '                                                                                <td align="right" class="td_top_line ">';
  template += '                                                                                    <p class="alignR">';
  template += '                                                                                        <b>' + totalgrossamount + '</b>';
  template += '                                                                                    </p>';
  template += '                                                                                </td>';
  template += '                                                                                ';
  template += '                                                                            </tr>-->';
  template += '                                                                            <!-- <tr>';
  template += '                                                                                <td class="td_top_line " colspan="35">';
  template += '                                                                                    <p class="alignL">';
  template += '                                                                                        <b>Amount in Words&nbsp;:&nbsp;${record.currencysymbol}&nbsp;${record.custbody_total_amount_in_words}</b>';
  template += '                                                                                    </p>';
  template += '                                                                                </td>';
  template += '                                                                            </tr> -->';

  template += '                                                                           ';
  // template+='</#list>';

  template += '                                                                      </table>';

  template += '<#if record.expense?has_content>';

  template += '  <#assign TotalAmount = 0/>';
  template += '<#list record.expense as expense>';

  template += '   <#if expense_index==0>';
  //template+='                                   <#if record.item?has_content>';
  template += '                                    <#assign SrNo=1><#assign totalsubtotalamount= 0>';
  template += '                                    <table style="width: 100%;margin-top:10px;" width="80%">                                                <!-- start items -->';
  template += '                                        ';
  template += '                                            <thead>';
  template += '                                                <tr style="padding-bottom: 0px;">';
  template += '                                                    <th align="left" width="1%" class="td_bottom_line">';
  template += '                                                        <p align="left"><b>sl</b></p>';
  template += '                                                    </th>';
  template += '                                                     <th align="right" width="5%" class="td_bottom_line">';
  template += '                                                        <p align="alignR"><b>Description</b></p>';
  template += '                                                    </th>';
  template += '                                                     <th align="right" width="10%" class="td_bottom_line">';
  template += '                                                        <p align="alignR"><b>Amount</b></p>';
  template += '                                                    </th>';
  template += '                                                     <th align="right" width="10%" class="td_bottom_line">';
  template += '                                                        <p align="alignR"><b>Tax Rate</b></p>';
  template += '                                                    </th>';
  template += '                                                     <th align="right" width="10%" class="td_bottom_line">';
  template += '                                                        <p align="alignR"><b>Tax Amount</b></p>';
  template += '                                                    </th>';
  template += '                                                     <th align="right" width="10%" class="td_bottom_line">';
  template += '                                                        <p align="alignR"><b>Gross Amount</b></p>';
  template += '                                                    </th>';
  template += '                                                </tr>';
  template += '                                            </thead>';
  template += '</#if>';
  // template+='<#list record.item as item>';
  // template+='<#assign totalsubtotalamount=totalsubtotalamount + item.grossamt/>';
  template += '                                                    <tr>';
  template += '                                                          <td align="left" class="">';
  template += '                                                            <p class="alignL">${expense_index + 1}</p>';
  template += '                                                        </td>';
  template += '                                                        <td align="right" class="">';
  template += '                                                            <p class="alignR"> ${expense.account}</p>';
  template += '                                                        </td>';
  template += '                                                                            ';
  template += '                                                        <td align="right" class="">             <!--total discount-->';
  template += '                                                            <p class="alignR">${expense.amount?string["#,##0.00"]}</p>';
  template += '                                                        </td>';
  template += '                                                         <td align="right" class="">             <!--charges-->';
  template += '                                                            <p class="alignR">${expense.taxrate1}</p>';
  template += '                                                        </td>';
  template += '';
  template += '                                                        <td align="right" class="">          <!--vat-->';
  template += '                                                            <p class="alignR">${expense.tax1amt?string["#,##0.00"]}</p>';
  template += '                                                        </td>';
  template += '                                                                               ';
  template += '                                                        <td align="right" class="">     <!--total-->';
  template += '<p class="alignR">${expense.grossamt?string["#,##0.00"]}</p>';
  template += '                                                 ';
  template += '                                                        </td>';
  template += '                                                                                ';
  template += '                                                    </tr>';
  template += '<#assign TotalAmount = TotalAmount + expense.amount/>';

  template += '    <#assign TotalGrossAmount = TotalGrossAmount + expense.grossamt />';

  template += '</#list>';
  template += '                                                                            <!-- <tr>';
  template += '                                                                                <td class="td_top_line " colspan="35">';
  template += '                                                                                    <p class="alignL">';
  template += '                                                                                        <b>Amount in Words&nbsp;:&nbsp;${record.currencysymbol}&nbsp;${record.custbody_total_amount_in_words}</b>';
  template += '                                                                                    </p>';
  template += '                                                                                </td>';
  template += '                                                                            </tr> -->';
  template += '                                                                           ';
  template += '                                    </table>';
  template += '</#if>';





  template += ' <table style="width: 70%;margin-top:10px;" width="100%">';
  template += ' <thead>';
  template += '<tr style="padding-bottom: 0px;">';
  template += '                                                    <th align="left" width="8%" class="td_bottom_line">';
  template += '                                                        <p align="left">';
  template += '                                                            <b>Currency</b>';
  template += '                                                        </p>';
  template += '                                                    </th>';
  template += '                                                    <th align="right" width="3%" class="td_bottom_line">';
  template += '                                                        <p align="alignR">';
  template += '                                                            <b>Purchase Subtotal amount</b>';
  template += '                                                        </p>';
  template += '                                                    </th>';
  // template+='                                                      <th align="right" width="8%" class="td_bottom_line">';
  // template+='                                                        <p align="alignR">';
  // template+='                                                            <b>total discount</b>';
  // template+='                                                        </p>';
  // template+='                                                    </th>                  ';
  template += '                                                    <th align="right" width="8%" class="td_bottom_line">';
  template += '                                                        <p align="alignR">';
  template += '                                                            <b>Charges</b>';
  template += '                                                        </p>';
  template += '                                                    </th>';
  template += '                                                    <th align="right" width="8%" class="td_bottom_line">';
  template += '                                                        <p align="alignR">';
  template += '                                                            <b>VAT</b>';
  template += '                                                        </p>';
  template += '                                                    </th>';
  template += '                                                    <th align="right" width="8%" class="td_bottom_line">';
  template += '                                                        <p align="alignR">';
  template += '                                                            <b>Total</b>';
  template += '                                                        </p>';
  template += '                                                    </th>';
  template += '</tr>';
  template += '  </thead>';
  template += '    <tr>                 ';
  template += '                                                         <td align="center" class="">';
  template += '                                                            <p class="alignC">${record.currency}</p>';
  template += '                                                        </td>';
  template += '                                                        <td align="center" class="">';
  template += '                                                            <p class="alignC">'+totalamount.toFixed(2)+'</p>';
  template += '                                                        </td>';
  // template+='                                                         <td align="center" class="">';
  // template+='                                                            <p class="alignC"></p>';
  // template+='                                                        </td>';
  template += '                                                        <td align="right" class="">';
  template += '                                                            <p class="alignR">${TotalAmount?string("##,#00.00")}</p>';
  template += '                                                        </td>';
  template += '                                                        <td align="right" class="">';
  template += '                                                            <p class="alignR">'+totaltax1amt.toFixed(2)+'</p>';
  template += '                                                        </td>';
  template += '                                                         <td align="right" class="">';
  template += '                                                            <p class="alignR">'+totalgrossamount.toFixed(2)+'</p>';
  template += '                                                        </td>';
  template += '  </tr> ';

  template += '  </table>                                                                  <!--    <table style="width: 100%;margin-top:15px;">';
  template += '                                                                             <tr>';
  template += '                                                                                 <td><b>Declaration:</b></td>';
  template += '                                                                        </tr>';
  template += '                                                                        <tr>';
  template += '                                                                                <td>We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct" to be';
  template += 'available in all invoices. Applicable to all the three operational subsidiaries</td>';
  template += '                                                                </tr>';
  template += '                                                                        </table>-->';
  template += '                                                                   </#if>';
  template += '                                                                    <!--<#if record.custbody_bank_account?has_content>';
  template += '<table style="width: 100%;margin-top:15px;">';
  template += '      <tr>';
  template += '        <th align="left" colspan="2" style="font-size:9pt;"><b>Please remit to</b></th>';
  template += '    </tr>';
  template += '    <tr>';
  template += '        <td align="left" colspan="2">Bank Name &nbsp;:&nbsp;${record.custbody_bank_account.custrecord_acc_bank_name}</td>';
  template += '    </tr>';
  template += '    <tr>';
  template += '        <td align="left" colspan="2">Country &nbsp;:&nbsp;${record.custbody_bank_account.custrecord_acc_country}</td>';
  template += '    </tr>';
  template += '    <tr>';
  template += '        <td align="left" colspan="2">Account Number &nbsp;:&nbsp;${record.custbody_bank_account.custrecord_acc_number}</td>';
  template += '    </tr>';
  template += '    <tr>';
  template += '        <td align="left" colspan="2">IBAN &nbsp;:&nbsp;${record.custbody_bank_account.custrecord_acc_iban}</td>';
  template += '    </tr>';
  template += '</table>';
  template += '</#if>-->';
  template += '';
  template += '<!--<table style="width: 100%;margin-top:20px;">';
  template += '    <tr>';
  template += '        <td align="left" width="25%">_____________________</td>';
  template += '        <td align="left" width="50%"></td>';
  template += '        <td  width="25%" align="center" style="margin-right:10px;">_____________________';
  template += '            </td>';
  template += '    </tr>';
  template += '     <tr>';
  template += '        <td align="left" width="20%"></td>';
  template += '        <td align="left" width="60%"></td>';
  template += '        <td align="center" style="margin-right:10px;">';
  template += '            <p style="margin-right:10px;padding-left:13px;font-weight:bold"><b>Received By</b></p></td>';
  template += '    </tr>';
  template += '      <tr>';
  template += '        <td align="left" width="20%"><b>Prepared by</b></td>';
  template += '        <td align="left" width="60%"></td>';
  template += '        <td align="center" style="margin-right:10px;">';
  template += '            <p style="margin-right:10px;padding-left:13px;font-weight:bold"></p></td>';
  template += '    </tr>';
  template += '</table>-->';
  template += '';
  template += '</body>';
  template += '</pdf>';
  renderer.setTemplate(template);
  renderer.addRecord('record', taxdebitnote);
  var xml = renderer.renderToString();
  var file = nlapiXMLToPDF(xml);
  response.setContentType('PDF', 'Check' + taxdebitnote.getFieldValue("id") + '.pdf', 'inline');
  response.write(file.getValue());
}
function relaceSlashN(charVal) {

  if (charVal) {

    return charVal.replace("\n", "<br />", "g");

  } else {

    return "";

  }
}
